### ISSUE TITLE
This issue is a todo list

### ISSUE THREAD

**Issue by Kritiqual** [Kritiqual/AwesomeWM#1]
Here is some todo currently wip:
- [ ] Make a bottom control board ?
- [ ] Dashboard like elenapan ?
- [ ] Make a exit screen
- [ ] Redesign hotkey popup (reference to worron config, awesome dracula by jeremie1001)
- [ ] ...
